/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import model.Encounter;
import model.Patient;
import model.PatientDirectory;
import model.SystemM;
import model.VitalSigns;

/**
 *
 * @author nidhitiwari
 */
public class MainJFrame extends javax.swing.JFrame {
    
    SystemM system;
    PatientDirectory patientDetails;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        system = new SystemM();
        addMultiplePatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddDocVisit = new javax.swing.JButton();
        btnViewCommunity = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddDocVisit.setText("Add Doctor Visit");
        btnAddDocVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocVisitActionPerformed(evt);
            }
        });

        btnViewCommunity.setText("Community Health Assessment");
        btnViewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDocVisit, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnViewCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnAddDocVisit)
                .addGap(44, 44, 44)
                .addComponent(btnViewCommunity)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDocVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocVisitActionPerformed
        DoctorVisit doctorPanel = new DoctorVisit(system);
        splitPane.setRightComponent(doctorPanel);
    }//GEN-LAST:event_btnAddDocVisitActionPerformed

    private void btnViewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunityActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(system);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewCommunityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    public void addMultiplePatient() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            LocalDate localDate = LocalDate.parse("12/12/1990", formatter);
            java.util.Date date=new java.util.Date(); 
            LocalDate dob = localDate;           
            Patient patient1 = new Patient(
            "Annie", 
            "Kalpa", 
            dob, 
            "2051", 
            "Dorchester",
            "Boston",  
            system.getPatientDirectory().size() + 1,
            system.getPersonDirectory().size() + 1
        );
                    
        Encounter encounter = null;
        VitalSigns vitals = new VitalSigns();
        vitals.setSysBP(Integer.parseInt("125"));
        vitals.setRespiratoryRate(Integer.parseInt("17"));
        vitals.setHeartRate(Integer.parseInt("110"));
        vitals.setWeightInKilos(Float.parseFloat("90"));
        encounter = new Encounter(vitals);
        patient1.getEncounterHistory().recordEncounter(encounter);
        
        system.addPatient(patient1);
        
        LocalDate localDate2 = LocalDate.parse("12/11/2000", formatter);
        LocalDate dob2 = localDate2;           
        Patient patient2 = new Patient(
        "Mike", 
        "Tyso", 
        dob2, 
        "1360", 
        "Beacon Hill",
        "Boston",  
        system.getPatientDirectory().size() + 1,
        system.getPersonDirectory().size() + 1
        );

        Encounter encounter2 = null;
        VitalSigns vitals2 = new VitalSigns();
        vitals2.setSysBP(Integer.parseInt("130"));
        vitals2.setRespiratoryRate(Integer.parseInt("20"));
        vitals2.setHeartRate(Integer.parseInt("120"));
        vitals2.setWeightInKilos(Float.parseFloat("70"));
        encounter2 = new Encounter(vitals2);
        patient2.getEncounterHistory().recordEncounter(encounter2);
        
        system.addPatient(patient2);
        
        LocalDate localDate3 = LocalDate.parse("12/11/2010", formatter);
        LocalDate dob3 = localDate3;           
        Patient patient3 = new Patient(
        "Chris", 
        "Royal", 
        dob3, 
        "1021", 
        "Beacon Hill",
        "Boston",  
        system.getPatientDirectory().size() + 1,
        system.getPersonDirectory().size() + 1
        );

        Encounter encounter3 = null;
        VitalSigns vitals3 = new VitalSigns();
        vitals3.setSysBP(Integer.parseInt("100"));
        vitals3.setRespiratoryRate(Integer.parseInt("15"));
        vitals3.setHeartRate(Integer.parseInt("102"));
        vitals3.setWeightInKilos(Float.parseFloat("55"));
        encounter3 = new Encounter(vitals3);
        patient3.getEncounterHistory().recordEncounter(encounter3);
        
        system.addPatient(patient3);
        
        LocalDate localDate4 = LocalDate.parse("12/11/1880", formatter);
        LocalDate dob4 = localDate4;           
        Patient patient4 = new Patient(
        "Jane", 
        "Sherman", 
        dob4, 
        "1125", 
        "Dorchester",
        "Boston",  
        system.getPatientDirectory().size() + 1,
        system.getPersonDirectory().size() + 1
        );

        Encounter encounter4 = null;
        VitalSigns vitals4 = new VitalSigns();
        vitals4.setSysBP(Integer.parseInt("128"));
        vitals4.setRespiratoryRate(Integer.parseInt("17"));
        vitals4.setHeartRate(Integer.parseInt("115"));
        vitals4.setWeightInKilos(Float.parseFloat("68"));
        encounter4 = new Encounter(vitals4);
        patient4.getEncounterHistory().recordEncounter(encounter4);
        
        system.addPatient(patient4);
        
        LocalDate localDate5 = LocalDate.parse("12/11/2016", formatter);
        LocalDate dob5 = localDate5;           
        Patient patient5 = new Patient(
        "Jenny", 
        "Rich", 
        dob5, 
        "1205", 
        "Beacon Hill",
        "Boston",  
        system.getPatientDirectory().size() + 1,
        system.getPersonDirectory().size() + 1
        );

        Encounter encounter5 = null;
        VitalSigns vitals5 = new VitalSigns();
        vitals5.setSysBP(Integer.parseInt("80"));
        vitals5.setRespiratoryRate(Integer.parseInt("15"));
        vitals5.setHeartRate(Integer.parseInt("70"));
        vitals5.setWeightInKilos(Float.parseFloat("21"));
        encounter5 = new Encounter(vitals5);
        patient5.getEncounterHistory().recordEncounter(encounter5);
        
        system.addPatient(patient5);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDocVisit;
    private javax.swing.JButton btnViewCommunity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
