/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Encounter;
import model.Patient;
import model.System;
import model.VitalSigns;

/**
 *
 * @author nidhitiwari
 */
public class UpdatePatient extends javax.swing.JPanel {
    
    System system;

    /**
     * Creates new form UpdatePatient
     */
    public UpdatePatient(System system) {
        initComponents();
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDOB = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblHouseNumber = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtBP = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtRespiratory = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblBP = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblRespiratory = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblCreateTitle = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblPatientID = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        lblDOB.setText("DOB");

        lblHouseNumber.setText("House Number");

        lblCommunity.setText("Community");

        lblCity.setText("City");

        lblWeight.setText("Weight");

        btnSave.setText("Update");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblBP.setText("BP");

        lblHeartRate.setText("Heart Rate");

        lblRespiratory.setText("Respiratory");

        lblCreateTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCreateTitle.setText("Update Patient Details");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblPatientID.setText("Enter Patient ID");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblPatientID)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLastName)
                        .addComponent(lblFirstName)
                        .addComponent(lblDOB)
                        .addComponent(lblHouseNumber)
                        .addComponent(lblCommunity)
                        .addComponent(lblCity)
                        .addComponent(lblBP)
                        .addComponent(lblHeartRate)
                        .addComponent(lblRespiratory)
                        .addComponent(lblWeight))
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFirstName)
                        .addComponent(txtLastName)
                        .addComponent(txtDOB)
                        .addComponent(txtHouseNumber)
                        .addComponent(txtCommunity)
                        .addComponent(txtCity)
                        .addComponent(txtBP)
                        .addComponent(txtHeartRate)
                        .addComponent(txtRespiratory)
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseNumber)
                    .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBP)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeartRate)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespiratory)
                    .addComponent(txtRespiratory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSave)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int patientID = getID();
        Patient patient1 = system.getPatientById(patientID);
        txtFirstName.setText(String.valueOf( patient1.getFirstName()));
        txtLastName.setText(String.valueOf( patient1.getLastName()));
        txtDOB.setText(String.valueOf(patient1.getDateOfBirth().toString()));
        txtCommunity.setText(String.valueOf(patient1.getResidence().getCommunityName()));
        txtHouseNumber.setText(String.valueOf(patient1.getResidence().getHouseNumber()));
        txtCity.setText(String.valueOf(patient1.getResidence().getCityName()));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int patientID = getID();
        Patient patient1 = system.getPatientById(patientID);

        Encounter encounter = null;
        VitalSigns vitals = new VitalSigns();
        vitals.setSysBP(Integer.parseInt(txtBP.getText()));
        if(txtRespiratory.getText() != null) {
           vitals.setRespiratoryRate(Integer.parseInt(txtRespiratory.getText())); 
        }
        if(txtHeartRate.getText() != null) {
           vitals.setRespiratoryRate(Integer.parseInt(txtHeartRate.getText())); 
        }
        if(txtWeight.getText() != null) {
           vitals.setRespiratoryRate(Integer.parseInt(txtWeight.getText())); 
        }
        encounter = new Encounter(vitals);
        patient1.getEncounterHistory().recordEncounter(encounter);
        
        JOptionPane.showMessageDialog(this, "Vital info Updated");
    }//GEN-LAST:event_btnSaveActionPerformed

    private int getID(){

    int patientID = Integer.parseInt(txtPatientId.getText());

    return patientID;
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblRespiratory;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtRespiratory;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
