/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import model.System;

/**
 *
 * @author nidhitiwari
 */
public class ViewJPanel extends javax.swing.JPanel {

    System system;
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(System system) {
        initComponents();
        this.system = system;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblModel = new javax.swing.JTable();
        btnAbnormalBP = new javax.swing.JButton();
        scrollAbnormal = new javax.swing.JScrollPane();
        tblAbnormal = new javax.swing.JTable();
        btnAbnormalRespRate = new javax.swing.JButton();
        btnAbnormalHeartRate = new javax.swing.JButton();
        btnAbnormalWeight = new javax.swing.JButton();

        jButton2.setText("Abnormal Vital Heart Rate");

        tblModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "DOB", "House Number", "Community", "City", "Age Group"
            }
        ));
        jScrollPane1.setViewportView(tblModel);

        btnAbnormalBP.setText("Abnormal BP");
        btnAbnormalBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalBPActionPerformed(evt);
            }
        });

        tblAbnormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Community", "Count", "Vital Sign"
            }
        ));
        scrollAbnormal.setViewportView(tblAbnormal);

        btnAbnormalRespRate.setText("Abnormal Vital Repiratory Rate");
        btnAbnormalRespRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalRespRateActionPerformed(evt);
            }
        });

        btnAbnormalHeartRate.setText("Abnormal Vital Heart Rate");
        btnAbnormalHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalHeartRateActionPerformed(evt);
            }
        });

        btnAbnormalWeight.setText("Abnormal Weight");
        btnAbnormalWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAbnormalBP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbnormalHeartRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbnormalRespRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbnormalWeight))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollAbnormal)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbnormalBP)
                    .addComponent(btnAbnormalRespRate)
                    .addComponent(btnAbnormalHeartRate)
                    .addComponent(btnAbnormalWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollAbnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbnormalBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalBPActionPerformed
                HashMap communityPatientMap =  system.showAbnoramlBPPatients();
                DefaultTableModel model = (DefaultTableModel) tblAbnormal.getModel();
                model.setRowCount(0);

                   communityPatientMap.forEach((key, value) -> {
                   Object [] row = new Object[10];
                   row[0] = key;
                   row[1] = value;
                model.addRow(row);

                    });
    }//GEN-LAST:event_btnAbnormalBPActionPerformed

    private void btnAbnormalHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalHeartRateActionPerformed
                HashMap communityPatientMap =  system.showAbnoramlHeartPatients();
                DefaultTableModel model = (DefaultTableModel) tblAbnormal.getModel();
                model.setRowCount(0);

                   communityPatientMap.forEach((key, value) -> {
                   Object [] row = new Object[10];
                   row[0] = key;
                   row[1] = value;
                   model.addRow(row);

                });
    }//GEN-LAST:event_btnAbnormalHeartRateActionPerformed

    private void btnAbnormalRespRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalRespRateActionPerformed
        HashMap communityPatientMap =  system.showAbnoramlRespiratoryPatients();
        DefaultTableModel model = (DefaultTableModel) tblAbnormal.getModel();
        model.setRowCount(0);

           communityPatientMap.forEach((key, value) -> {
           Object [] row = new Object[10];
           row[0] = key;
           row[1] = value;
           model.addRow(row);

        });
    }//GEN-LAST:event_btnAbnormalRespRateActionPerformed

    private void btnAbnormalWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalWeightActionPerformed
        HashMap communityPatientMap =  system.showAbnoramlWeightPatients();
        DefaultTableModel model = (DefaultTableModel) tblAbnormal.getModel();
        model.setRowCount(0);

           communityPatientMap.forEach((key, value) -> {
           Object [] row = new Object[10];
           row[0] = key;
           row[1] = value;
           model.addRow(row);

        });
    }//GEN-LAST:event_btnAbnormalWeightActionPerformed

    private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblModel.getModel();
    model.setRowCount(0);
     java.lang.System.out.println(system.getPatientById(0));
    system.getPatientDirectory().forEach(patient -> {
        Object [] row = new Object[10];
        row[0] = patient.getPersonId();
        row[1] = patient.getFirstName()+" "+patient.getLastName();
        row[2] = patient.getDateOfBirth().toString();
        row[3] = patient.getAgeGroup().toString();
        row[5] = patient.getResidence().getHouseNumber();
        row[6] = patient.getResidence().getCommunityName();
        row[4] = patient.getResidence().getCityName();

        model.addRow(row);
    });        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbnormalBP;
    private javax.swing.JButton btnAbnormalHeartRate;
    private javax.swing.JButton btnAbnormalRespRate;
    private javax.swing.JButton btnAbnormalWeight;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollAbnormal;
    private javax.swing.JTable tblAbnormal;
    private javax.swing.JTable tblModel;
    // End of variables declaration//GEN-END:variables
}
